#Hitreg Settings

#Configure
hitreg=0
metronome=0
muffle_amount=0
sharpen_amount=0

#Render
cross_far_color=FFFFFF
cross_far_color_with_hitbox=0000FF
cross_near_color=FF0000
cross_near_color_with_hitbox=0000FF
cross_opacity=255
hitbox_far_color=FFFFFF
hitbox_near_color=FF0000
hitbox_opacity=255
jump_reset_color=FFFF00
jump_reset_opacity=255
perfect_hit_color=00FF00
perfect_hit_opacity=255
server_hitbox_opacity=125
their_jump_far_color=007FFF
their_jump_near_color=007FFF
their_jump_range_opacity=255
their_reach_far_color=FFFFFF
their_reach_near_color=FF0000
their_reach_opacity=255
your_jump_far_color=007FFF
your_jump_near_color=007FFF
your_jump_range_opacity=255
your_reach_far_color=FFFFFF
your_reach_near_color=FF0000
your_reach_opacity=255

#UI
background_color=000000
background_opacity=230
border_color=646464
border_opacity=255
highlighted_color=FFE350
highlighted_opacity=255
hovered_color=FFF3A6
hovered_opacity=255
text_color=DEDEDE
text_opacity=255

#Tracked
fight_playtime_(seconds)=1577
total_fights=20

#Toggle
alertDelays=false
alertFights=false
alertGhosts=false
alertInconsistencies=false
hideAllParticles=false
hideAnimations=false
hideArmor=false
hideOtherFights=false
hideOtherParticles=false
ignoreShieldHolders=false
JumpResetColor=false
legacySounds=false
particlesEveryHit=false
PerfectHitColor=false
renderCross=false
renderHitbox=false
RenderServerHitbox=false
RenderTheirJump=false
RenderTheirReach=false
RenderYourJump=false
RenderYourReach=false
safeRegsOnly=true
silenceNonHits=false
silenceOtherFights=false
silenceSelf=false
silenceThem=false
toggle=true
tutorial=true

